image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

platform:
  - Any CPU

configuration:
  - Release

assembly_info:
  patch: false

dotnet_csproj:
  patch: true
  file: 'src\GitTools.IssueTrackers\GitTools.IssueTrackers.csproj'
  version: $(GitVersion_FullSemVer)
  package_version: $(GitVersion_FullSemVer)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemVer)
  informational_version: $(GitVersion_FullSemVer)


before_build:
  - nuget restore src\
  - ps: gitversion /l console /output buildserver

build:
  project: src\GitTools.IssueTrackers.sln

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
